import About from "@/components/About/About";
import Card from "@/components/Card/Card";
import Navigation from "@/components/Navigation/Navigation";
import Socials from "@/components/Socials/Socials";
import DividerTitle from "@/components/typography/DividerTitle/DividerTitle";
import Head from "next/head";
import React from "react";

const about = () => {
  return (
    <>
      <Head>
        <title>Louby Lou</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <About
          title={"Who exactly is Louby Lou?"}
          body={[
            "Louby lou is Quisque sit amet luctus enim. Sed vel urna porta, gravida tellus eu, consequat justo. Nulla iaculis blandit fermentum. Vivamus metus justo, ultricies sit amet placerat non, aliquam ac ante. Donec semper mauris mi, quis pellentesque erat pretium sed. Cras sed sagittis lacus.",
          ]}
          spacer
        />
        <Card
          title={"Why Louby Lou?"}
          desc={[
            "This is a test description, just for looking at sake, I would use lorem ipsum but I feel like that's overused",
            "Now this is just an example of another paragraph, separated using an array rather than just plain text",
          ]}
          pos={"right"}
          img={"/images/pictures/lucy_about_me.jpeg"}
        />
        <DividerTitle
          title={"Want to keep in the loop?"}
          text={[
            "Scroll down to find my socials, or check the bottom of the page for my personal contact details!",
          ]}
        />
        <Socials />
      </main>
    </>
  );
};

export default about;
