import Companies from "@/components/Companies/Companies";
import Gallery from "@/components/Gallery/Gallery";
import Navigation from "@/components/Navigation/Navigation";
import Socials from "@/components/Socials/Socials";
import DividerTitle from "@/components/typography/DividerTitle/DividerTitle";
import Head from "next/head";
import React from "react";

const gallery = () => {
  return (
    <>
      <Head>
        <title>Louby Lou</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <DividerTitle
          title={"welcome to louby lou's gallery"}
          text={["For all things louby lou"]}
          spacing={"large"}
        />
        <Gallery />
        <Socials />
        <Companies />
      </main>
    </>
  );
};

export default gallery;
