import Head from "next/head";
import Hero from "@/components/Hero/Hero";
import Navigation from "@/components/Navigation/Navigation";

export default function Home({ pets }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Hero />
    </>
  );
}
