import About from "@/components/About/About";
import Decoration from "@/components/Decoration/Decoration";
import Navigation from "@/components/Navigation/Navigation";
import PackageDetails from "@/components/PackageDetails/PackageDetails";
import Packages from "@/components/Packages/Packages";
import Pricing from "@/components/Pricing/Pricing";
import Socials from "@/components/Socials/Socials";
import DividerTitle from "@/components/typography/DividerTitle/DividerTitle";
import Title from "@/components/typography/Title/Title";
import Head from "next/head";
import React from "react";

const pricing = () => {
  return (
    <>
      <Head>
        <title>Louby Lou</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DividerTitle
          title="what package is best for you?"
          text={["Look no further!"]}
        />
        <Decoration position={"right"} />
        <Navigation />
        <Packages />
        <PackageDetails />
        <DividerTitle title={""} text={[""]} />
        <Socials />
      </main>
    </>
  );
};

export default pricing;
