import Navigation from "@/components/Navigation/Navigation";
import Pricing from "@/components/Pricing/Pricing";
import Socials from "@/components/Socials/Socials";
import DividerTitle from "@/components/typography/DividerTitle/DividerTitle";
import Head from "next/head";
import React from "react";
import pricingJSON from "./api/json/packages.json";
import PricingContainer from "@/components/PricingContainer/PricingContainer";
import About from "@/components/About/About";
import Companies from "@/components/Companies/Companies";

export async function getStaticProps() {
  const pricingData = await pricingJSON;
  return {
    props: {
      pricingData,
    },
  };
}

const pricing = ({ pricingData }) => {
  return (
    <>
      <Head>
        <title>Louby Lou</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <About
          title={"Looking to book?"}
          body={[
            "Look no further!",
            "Have a look at my packages! Can't find what you're looking for? Feel free to get in touch!",
          ]}
        />
        <PricingContainer data={pricingData} />
        <DividerTitle
          title={"Use this as a divider"}
          text={["It's really a great way to break up the page!"]}
        />
        <Socials />
        <Companies />
      </main>
    </>
  );
};

export default pricing;
