import Card from "@/components/Card/Card";
import Decoration from "@/components/Decoration/Decoration";
import Navigation from "@/components/Navigation/Navigation";
import Pricing from "@/components/Pricing/Pricing";
import Socials from "@/components/Socials/Socials";
import DividerTitle from "@/components/typography/DividerTitle/DividerTitle";
import Head from "next/head";
import React from "react";

const services = () => {
  function isInt(n) {
    if (Number.isInteger(n) === true) {
      return "left";
    } else {
      return "right";
    }
  }
  let array = [1, 2, 3, 4, 5];
  return (
    <>
      <Head>
        <title>Louby Lou</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navigation />
        <DividerTitle
          title={"What can Louby Lou do for you?"}
          text={["There's always a little something for everyone!"]}
        />
        <Decoration position={"right"} />
        {array.map((item, idx) => (
          <Card
            title={`title card ${item}`}
            desc={[
              "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis metus diam, ultrices at lectus vitae, tempor ullamcorper arcu. Sed pulvinar at tellus sit amet consectetur. Phasellus rutrum sollicitudin urna ac feugiat. Sed eleifend commodo risus, quis posuere justo.",
              "Quisque sit amet luctus enim. Sed vel urna porta, gravida tellus eu, consequat justo. Nulla iaculis blandit fermentum. Vivamus metus justo, ultricies sit amet placerat non, aliquam ac ante. Donec semper mauris mi, quis pellentesque erat pretium sed. Cras sed sagittis lacus.",
            ]}
            pos={isInt(idx / 2)}
            img={"/images/pictures/lucy_about_me.jpeg"}
          />
        ))}
        <Socials />
      </main>
    </>
  );
};

export default services;
